/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fasten.your.seatbelt.forms;

/**
 *
 * @author Joost
 */
public class LogIn extends javax.swing.JFrame
{

    /**
     * Creates new form LogIn
     */
    public LogIn()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        logInScreen = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        signIn = new javax.swing.JButton();
        rememberMe = new javax.swing.JCheckBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        logInScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        username.setText("Username :");
        logInScreen.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.setText("Password :");
        logInScreen.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        usernameInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                usernameInputActionPerformed(evt);
            }
        });
        logInScreen.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, -1));

        passwordInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordInputActionPerformed(evt);
            }
        });
        logInScreen.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, -1));

        signIn.setText("Sign in");
        signIn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signInActionPerformed(evt);
            }
        });
        logInScreen.add(signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 20));

        rememberMe.setText("Remember me");
        logInScreen.add(rememberMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fasten/your/seatbelt/Images/LogInScreen.jpg"))); // NOI18N
        logInScreen.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logInScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logInScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_usernameInputActionPerformed
    {//GEN-HEADEREND:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signInActionPerformed
    {//GEN-HEADEREND:event_signInActionPerformed
        String user = usernameInput.getText();
        String password = passwordInput.getText();
        if (user.equals("Counter"))
        {
            dispose();
            Counter counter = new Counter();
            counter.setVisible(true);
        } else if (user.equals("Manager"))
        {
            dispose();
            Manager manager = new Manager();
            manager.setVisible(true);
        } else if (user.equals("AppManager"))
        {
            dispose();
            ApplicationManager appManager = new ApplicationManager();
            appManager.setVisible(true);
        }
    }//GEN-LAST:event_signInActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordInputActionPerformed
    {//GEN-HEADEREND:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LogIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel logInScreen;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JCheckBox rememberMe;
    private javax.swing.JButton signIn;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
