/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.ManagerOverview;

/**
 *
 * @author Jeff
 */
public class ManagerUI extends javax.swing.JFrame
{

    /**
     * Creates new form ManagerUI
     */
    public ManagerUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        OverviewPanel = new javax.swing.JTabbedPane();
        currentStatPanel = new javax.swing.JPanel();
        currentInfoPanel = new javax.swing.JPanel();
        currentTextPanel = new javax.swing.JPanel();
        currentBMissingNum = new javax.swing.JLabel();
        currentTotal = new javax.swing.JLabel();
        currentBFoundNum = new javax.swing.JLabel();
        currentBFound = new javax.swing.JLabel();
        currentBMissing = new javax.swing.JLabel();
        currentTotalNum = new javax.swing.JLabel();
        currentGraphPanel = new javax.swing.JPanel();
        pieChart = new javax.swing.JLabel();
        overviewPanel = new javax.swing.JPanel();
        overviewInfoPanel = new javax.swing.JPanel();
        yearBox = new javax.swing.JComboBox();
        yearText = new javax.swing.JLabel();
        overviewTextPanel = new javax.swing.JPanel();
        overviewProcessed = new javax.swing.JLabel();
        overviewFoundNum = new javax.swing.JLabel();
        overviewFound = new javax.swing.JLabel();
        overviewTotal = new javax.swing.JLabel();
        overviewTotalNum = new javax.swing.JLabel();
        overviewMissing = new javax.swing.JLabel();
        overviewMissingNum = new javax.swing.JLabel();
        overviewProcessedNum = new javax.swing.JLabel();
        overviewGraphPanel = new javax.swing.JPanel();
        lineChart = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        currentStatPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        currentInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sunday, 13 October"));
        currentInfoPanel.setPreferredSize(new java.awt.Dimension(600, 135));

        currentBMissingNum.setText("195");

        currentTotal.setText("Total:");

        currentBFoundNum.setText("56");

        currentBFound.setText("Amount of baggage found:");

        currentBMissing.setText("Amount of baggage missing:");

        currentTotalNum.setText("251");

        javax.swing.GroupLayout currentTextPanelLayout = new javax.swing.GroupLayout(currentTextPanel);
        currentTextPanel.setLayout(currentTextPanelLayout);
        currentTextPanelLayout.setHorizontalGroup(
            currentTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentBMissing, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(currentBFound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(currentTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentTotalNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(currentBMissingNum)
                    .addComponent(currentBFoundNum, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        currentTextPanelLayout.setVerticalGroup(
            currentTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentBMissing)
                    .addComponent(currentBMissingNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(currentTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentBFound)
                    .addComponent(currentBFoundNum))
                .addGap(18, 18, 18)
                .addGroup(currentTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentTotalNum)
                    .addComponent(currentTotal))
                .addContainerGap())
        );

        javax.swing.GroupLayout currentInfoPanelLayout = new javax.swing.GroupLayout(currentInfoPanel);
        currentInfoPanel.setLayout(currentInfoPanelLayout);
        currentInfoPanelLayout.setHorizontalGroup(
            currentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentInfoPanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(currentTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        currentInfoPanelLayout.setVerticalGroup(
            currentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentTextPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pieChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fasten/your/seatbelt/Images/piechart.png"))); // NOI18N

        javax.swing.GroupLayout currentGraphPanelLayout = new javax.swing.GroupLayout(currentGraphPanel);
        currentGraphPanel.setLayout(currentGraphPanelLayout);
        currentGraphPanelLayout.setHorizontalGroup(
            currentGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieChart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        currentGraphPanelLayout.setVerticalGroup(
            currentGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieChart)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout currentStatPanelLayout = new javax.swing.GroupLayout(currentStatPanel);
        currentStatPanel.setLayout(currentStatPanelLayout);
        currentStatPanelLayout.setHorizontalGroup(
            currentStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentStatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(currentGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        currentStatPanelLayout.setVerticalGroup(
            currentStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentStatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        OverviewPanel.addTab("Current Stats", currentStatPanel);

        overviewInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        overviewInfoPanel.setPreferredSize(new java.awt.Dimension(600, 135));

        yearBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2012", "2011", "2010", "2009", "2008", "2007" }));

        yearText.setText("Select year");

        overviewProcessed.setText("Amount of baggage processed:");

        overviewFoundNum.setText("56");

        overviewFound.setText("Amount of baggage found:");

        overviewTotal.setText("Total:");

        overviewTotalNum.setText("274");

        overviewMissing.setText("Amount of baggage missing:");

        overviewMissingNum.setText("195");

        overviewProcessedNum.setText("23");

        javax.swing.GroupLayout overviewTextPanelLayout = new javax.swing.GroupLayout(overviewTextPanel);
        overviewTextPanel.setLayout(overviewTextPanelLayout);
        overviewTextPanelLayout.setHorizontalGroup(
            overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewProcessed)
                    .addComponent(overviewTotal)
                    .addComponent(overviewMissing)
                    .addComponent(overviewFound))
                .addGap(100, 100, 100)
                .addGroup(overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewTotalNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(overviewMissingNum)
                    .addComponent(overviewFoundNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(overviewProcessedNum, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );
        overviewTextPanelLayout.setVerticalGroup(
            overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewMissing)
                    .addComponent(overviewMissingNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewFound)
                    .addComponent(overviewFoundNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewProcessed)
                    .addComponent(overviewProcessedNum))
                .addGap(18, 18, 18)
                .addGroup(overviewTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewTotalNum)
                    .addComponent(overviewTotal))
                .addContainerGap())
        );

        javax.swing.GroupLayout overviewInfoPanelLayout = new javax.swing.GroupLayout(overviewInfoPanel);
        overviewInfoPanel.setLayout(overviewInfoPanelLayout);
        overviewInfoPanelLayout.setHorizontalGroup(
            overviewInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewInfoPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(yearText)
                .addGap(29, 29, 29)
                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overviewTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        overviewInfoPanelLayout.setVerticalGroup(
            overviewInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearText)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewInfoPanelLayout.createSequentialGroup()
                .addComponent(overviewTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        lineChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fasten/your/seatbelt/Images/linechart.png"))); // NOI18N

        javax.swing.GroupLayout overviewGraphPanelLayout = new javax.swing.GroupLayout(overviewGraphPanel);
        overviewGraphPanel.setLayout(overviewGraphPanelLayout);
        overviewGraphPanelLayout.setHorizontalGroup(
            overviewGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineChart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overviewGraphPanelLayout.setVerticalGroup(
            overviewGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineChart, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(overviewInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(overviewGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(overviewInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overviewGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        OverviewPanel.addTab("Year Overview", overviewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OverviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OverviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
            {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                {
                if ("Nimbus".equals(info.getName()))
                    {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    }
                }
            } catch (ClassNotFoundException ex)
            {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex)
            {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex)
            {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex)
            {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ManagerUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane OverviewPanel;
    private javax.swing.JLabel currentBFound;
    private javax.swing.JLabel currentBFoundNum;
    private javax.swing.JLabel currentBMissing;
    private javax.swing.JLabel currentBMissingNum;
    private javax.swing.JPanel currentGraphPanel;
    private javax.swing.JPanel currentInfoPanel;
    private javax.swing.JPanel currentStatPanel;
    private javax.swing.JPanel currentTextPanel;
    private javax.swing.JLabel currentTotal;
    private javax.swing.JLabel currentTotalNum;
    private javax.swing.JLabel lineChart;
    private javax.swing.JLabel overviewFound;
    private javax.swing.JLabel overviewFoundNum;
    private javax.swing.JPanel overviewGraphPanel;
    private javax.swing.JPanel overviewInfoPanel;
    private javax.swing.JLabel overviewMissing;
    private javax.swing.JLabel overviewMissingNum;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JLabel overviewProcessed;
    private javax.swing.JLabel overviewProcessedNum;
    private javax.swing.JPanel overviewTextPanel;
    private javax.swing.JLabel overviewTotal;
    private javax.swing.JLabel overviewTotalNum;
    private javax.swing.JLabel pieChart;
    private javax.swing.JComboBox yearBox;
    private javax.swing.JLabel yearText;
    // End of variables declaration//GEN-END:variables
}
